// scaffolding-vs-ai-generation/experiments/nextjs/manual/app/page.tsx
"use client";

import { useState } from "react";

interface Task {
  id: number;
  text: string;
  completed: boolean;
}

export default function Home() {
  const [tasks, setTasks] = useState<Task[]>([
    { id: 1, text: "Learn Next.js", completed: false },
    { id: 2, text: "Build a ToDo app", completed: true },
  ]);
  const [newTask, setNewTask] = useState("");

  const addTask = () => {
    if (newTask.trim()) {
      setTasks([
        ...tasks,
        { id: Date.now(), text: newTask, completed: false },
      ]);
      setNewTask("");
    }
  };

  const toggleTask = (id: number) => {
    setTasks(
      tasks.map((task) =>
        task.id === id ? { ...task, completed: !task.completed } : task
      )
    );
  };

  const deleteTask = (id: number) => {
    setTasks(tasks.filter((task) => task.id !== id));
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 dark:from-gray-900 dark:to-gray-800 py-8 px-4">
      <main className="max-w-2xl mx-auto">
        <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
          <h1 className="text-3xl font-bold text-gray-800 dark:text-white mb-6">
            My Tasks
          </h1>

          <div className="flex gap-2 mb-6">
            <input
              type="text"
              value={newTask}
              onChange={(e) => setNewTask(e.target.value)}
              onKeyPress={(e) => e.key === "Enter" && addTask()}
              placeholder="Add a new task..."
              className="flex-1 px-4 py-2 border border-gray-300 dark:border-gray-600 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-500 dark:bg-gray-700 dark:text-white"
            />
            <button
              onClick={addTask}
              className="px-6 py-2 bg-blue-500 text-white rounded-lg hover:bg-blue-600 transition-colors"
            >
              Add
            </button>
          </div>

          <ul className="space-y-2">
            {tasks.map((task) => (
              <li
                key={task.id}
                className="flex items-center gap-3 p-3 bg-gray-50 dark:bg-gray-700 rounded-lg"
              >
                <input
                  type="checkbox"
                  checked={task.completed}
                  onChange={() => toggleTask(task.id)}
                  className="w-5 h-5 text-blue-500 rounded focus:ring-2 focus:ring-blue-500"
                />
                <span
                  className={`flex-1 ${
                    task.completed
                      ? "line-through text-gray-400"
                      : "text-gray-800 dark:text-white"
                  }`}
                >
                  {task.text}
                </span>
                <button
                  onClick={() => deleteTask(task.id)}
                  className="px-3 py-1 text-red-500 hover:bg-red-50 dark:hover:bg-red-900 rounded transition-colors"
                >
                  Delete
                </button>
              </li>
            ))}
          </ul>

          {tasks.length === 0 && (
            <p className="text-center text-gray-400 py-8">
              No tasks yet. Add one above!
            </p>
          )}
        </div>

        <div className="mt-6 text-center text-sm text-gray-600 dark:text-gray-400">
          <p>Total: {tasks.length} | Completed: {tasks.filter(t => t.completed).length}</p>
        </div>
      </main>
    </div>
  );
}

// scaffolding-vs-ai-generation/experiments/angular/manual/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface Task {
  id: number;
  text: string;
  completed: boolean;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ToDo App';
  tasks: Task[] = [
    { id: 1, text: 'Learn Angular', completed: false },
    { id: 2, text: 'Build a ToDo app', completed: true }
  ];
  newTask = '';

  addTask(): void {
    if (this.newTask.trim()) {
      this.tasks.push({
        id: Date.now(),
        text: this.newTask,
        completed: false
      });
      this.newTask = '';
    }
  }

  toggleTask(task: Task): void {
    task.completed = !task.completed;
  }

  deleteTask(id: number): void {
    this.tasks = this.tasks.filter(task => task.id !== id);
  }

  get completedCount(): number {
    return this.tasks.filter(t => t.completed).length;
  }
}

<div class="app">
  <div class="container">
    <h1>{{ title }}</h1>

    <div class="input-group">
      <input
        type="text"
        [(ngModel)]="newTask"
        (keyup.enter)="addTask()"
        placeholder="Add a new task..."
      />
      <button (click)="addTask()">Add</button>
    </div>

    <ul class="task-list">
      <li *ngFor="let task of tasks" [class.completed]="task.completed">
        <input
          type="checkbox"
          [checked]="task.completed"
          (change)="toggleTask(task)"
        />
        <span>{{ task.text }}</span>
        <button (click)="deleteTask(task.id)">Delete</button>
      </li>
    </ul>

    <p *ngIf="tasks.length === 0" class="empty">No tasks yet. Add one above!</p>

    <div class="stats">
      Total: {{ tasks.length }} | Completed: {{ completedCount }}
    </div>
  </div>
</div>
