// scaffolding-vs-ai-generation/experiments/vite-react/manual/src/App.tsx
import { useState } from 'react'
import './App.css'

interface Task {
  id: number;
  text: string;
  completed: boolean;
}

function App() {
  const [tasks, setTasks] = useState<Task[]>([
    { id: 1, text: "Learn Vite", completed: false },
    { id: 2, text: "Build a ToDo app", completed: true },
  ]);
  const [newTask, setNewTask] = useState("");

  const addTask = () => {
    if (newTask.trim()) {
      setTasks([...tasks, { id: Date.now(), text: newTask, completed: false }]);
      setNewTask("");
    }
  };

  const toggleTask = (id: number) => {
    setTasks(tasks.map(task =>
      task.id === id ? { ...task, completed: !task.completed } : task
    ));
  };

  const deleteTask = (id: number) => {
    setTasks(tasks.filter(task => task.id !== id));
  };

  return (
    <div className="app">
      <div className="container">
        <h1>My Tasks</h1>

        <div className="input-group">
          <input
            type="text"
            value={newTask}
            onChange={(e) => setNewTask(e.target.value)}
            onKeyPress={(e) => e.key === "Enter" && addTask()}
            placeholder="Add a new task..."
          />
          <button onClick={addTask}>Add</button>
        </div>

        <ul className="task-list">
          {tasks.map((task) => (
            <li key={task.id} className={task.completed ? "completed" : ""}>
              <input
                type="checkbox"
                checked={task.completed}
                onChange={() => toggleTask(task.id)}
              />
              <span>{task.text}</span>
              <button onClick={() => deleteTask(task.id)}>Delete</button>
            </li>
          ))}
        </ul>

        {tasks.length === 0 && <p className="empty">No tasks yet. Add one above!</p>}

        <div className="stats">
          Total: {tasks.length} | Completed: {tasks.filter(t => t.completed).length}
        </div>
      </div>
    </div>
  )
}

export default App

// scaffolding-vs-ai-generation/experiments/angular/manual/src/app/app.component.ts
import { Component } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';

interface Task {
  id: number;
  text: string;
  completed: boolean;
}

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, FormsModule],
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'ToDo App';
  tasks: Task[] = [
    { id: 1, text: 'Learn Angular', completed: false },
    { id: 2, text: 'Build a ToDo app', completed: true }
  ];
  newTask = '';

  addTask(): void {
    if (this.newTask.trim()) {
      this.tasks.push({
        id: Date.now(),
        text: this.newTask,
        completed: false
      });
      this.newTask = '';
    }
  }

  toggleTask(task: Task): void {
    task.completed = !task.completed;
  }

  deleteTask(id: number): void {
    this.tasks = this.tasks.filter(task => task.id !== id);
  }

  get completedCount(): number {
    return this.tasks.filter(t => t.completed).length;
  }
}

<div class="app">
  <div class="container">
    <h1>{{ title }}</h1>

    <div class="input-group">
      <input
        type="text"
        [(ngModel)]="newTask"
        (keyup.enter)="addTask()"
        placeholder="Add a new task..."
      />
      <button (click)="addTask()">Add</button>
    </div>

    <ul class="task-list">
      <li *ngFor="let task of tasks" [class.completed]="task.completed">
        <input
          type="checkbox"
          [checked]="task.completed"
          (change)="toggleTask(task)"
        />
        <span>{{ task.text }}</span>
        <button (click)="deleteTask(task.id)">Delete</button>
      </li>
    </ul>

    <p *ngIf="tasks.length === 0" class="empty">No tasks yet. Add one above!</p>

    <div class="stats">
      Total: {{ tasks.length }} | Completed: {{ completedCount }}
    </div>
  </div>
</div>
